apiVersion: v1
kind: Service
metadata:
  name: game-catalog
  namespace: leprecon
  labels:
    app: game-catalog
    service: game-catalog
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: game-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-catalog
  namespace: leprecon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-catalog
      version: v1
  template:
    metadata:
      labels:
        app: game-catalog
        version: v1
    spec:
      containers:
        - image: ghcr.io/leprec0n/microservices/game_catalog:latest
          imagePullPolicy: Always
          name: game-catalog
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: game-catalog-secret
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: game-catalog-hpa
  namespace: leprecon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: game-catalog
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
---
apiVersion: v1
kind: Service
metadata:
  name: game-catalog-database-service
  namespace: leprecon
spec:
  selector:
    app: game-catalog-database
  ports:
    - port: 27017
      targetPort: catalog-db-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-catalog-database
  namespace: leprecon
spec:
  selector:
    matchLabels:
      app: game-catalog-database
  template:
    metadata:
      labels:
        app: game-catalog-database
    spec:
      containers:
        - name: game-catalog-database
          image: mongodb/mongodb-community-server:7.0-ubi8
          ports:
            - containerPort: 27017
              name: catalog-db-port
