name: Game_Catalog
run-name: "${{ github.actor }} ran ${{ github.workflow }} on ${{ github.ref_name }}"
on:
  push:
    branches:
      - '\d+-*'
      - development
    paths:
      - "src/game_catalog/**"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "src/game_catalog/**"
jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    if: github.base_ref == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Build docker image
        run: docker build -t 'ghcr.io/${{ github.repository }}/game_catalog' -f src/game_catalog/Dockerfile .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Push to GitHub Container Registry
        run: docker push 'ghcr.io/${{ github.repository }}/game_catalog:latest'
